services:
  login-service:
    image: lw89233/login-service:latest
    container_name: login-service
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${LOGIN_MICROSERVICE_PORT}:${LOGIN_MICROSERVICE_PORT}"